from .HellrunnersMagicalNodes import NODE_CLASS_MAPPINGS as HMN_C_Map, NODE_DISPLAY_NAME_MAPPINGS as HMN_N_Map
from .Mojo import NODE_CLASS_MAPPINGS as MOJ_C_Map, NODE_DISPLAY_NAME_MAPPINGS as MOJ_N_Map

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **HMN_C_Map}
NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **MOJ_C_Map}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **HMN_N_Map}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **MOJ_N_Map}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
